[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "insurance-bot"
version = "1.0.0"
description = "Telegram bot for car insurance"
requires-python = ">=3.11"
authors = [
    {name = "hmaksymm"}
]

[tool.setuptools]
packages = ["."] 